### ISSUE TITLE
How to use this tool

### ISSUE THREAD

**Issue by liukun4515** [DistributedClocks/DistributedClocks.github.io#1]
I want to use this tool in the distributed system Cassandra.
Should I modify the source code in the Cassandra or not?
If not, what should I do to use this tool in this system?

**Comment by bestchai** [comment]
Usage varies slightly depending on language. e.g., Java usage is different from C++ usage. In general the libraries require you to modify the source code of the system (i.e., to instrument it). This means that you need to identify locations in the code where the system performs communication (e.g., message sends and receives) and wrap these to support vector clocks. 

The one exception to the above is Go lang. For Go systems we have a tool to automatically perform instrumentation.
